import React from 'react'
import styles from '../../styles/Home.module.css'
import Head from 'next/head'

function test1() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='http://www.kbsly.com/.well-known/assetlinks.json' style={{textDecorationLine:'none'}}>TEST1 with http!</a>
        </h1>
        <h1>
          Welcome to <a href='https://www.kbsly.com/.well-known/assetlinks.json' style={{textDecorationLine:'none'}}>TEST1 with https!</a>
        </h1>

      </main>

   
    </div>
  )
}

export default test1